In [86]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

***EJERCICIO UNO***

In [87]:
# Cargar datos
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columnas = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 
            'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']
data = pd.read_csv(url, names=columnas)
print(f"Datos cargados: {data.shape[0]} filas y {data.shape[1]} columnas")
print(data.head())


Datos cargados: 768 filas y 9 columnas
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [88]:
# Separar características y objetivo
X = data.drop('Outcome', axis=1)
y = data['Outcome']

# Dividir datos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Crear y entrenar modelo
from sklearn.linear_model import LogisticRegression
modelo = LogisticRegression(max_iter=1000)
modelo.fit(X_train, y_train)



LogisticRegression(max_iter=1000)

In [89]:
# Predecir y evaluar
y_pred = modelo.predict(X_test)
print("Exactitud:", accuracy_score(y_test, y_pred))
print("\nMatriz de confusión:\n", confusion_matrix(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))

Exactitud: 0.7359307359307359

Matriz de confusión:
 [[120  31]
 [ 30  50]]

Reporte de clasificación:
               precision    recall  f1-score   support

           0       0.80      0.79      0.80       151
           1       0.62      0.62      0.62        80

    accuracy                           0.74       231
   macro avg       0.71      0.71      0.71       231
weighted avg       0.74      0.74      0.74       231



***EJERCICIO DOS***

In [90]:
# Generar datos sintéticos
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=500, n_features=6, n_informative=3, random_state=42)

print(f"Datos sintéticos generados: {X.shape[0]} filas y {X.shape[1]} columnas")
print(f"\nDatos X:\n{X[:5]}")
print(f"\nDatos y:\n{y[:5]}")

Datos sintéticos generados: 500 filas y 6 columnas

Datos X:
[[-0.31851354 -0.18212768  0.98189351 -1.60755986  1.68024248  1.54019374]
 [ 1.02863791  0.23370842  1.92305486  0.59355672  1.94966773  0.69511557]
 [-0.57377375 -1.08206271 -0.71929701 -0.65000258 -0.76656838  0.30967909]
 [ 0.25853845 -0.72956006 -0.96833186 -0.4473219  -1.79488211 -1.14910848]
 [ 1.2389431   0.29642151  1.94297847  0.65924567  1.80556309  0.42547177]]

Datos y:
[1 1 0 0 1]


In [91]:
# Crear y entrenar modelo
modelo = LogisticRegression(max_iter=1000)
modelo.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [92]:
# Evaluar modelo
y_pred = modelo.predict(X_test)
print("Exactitud:", accuracy_score(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))

Exactitud: 0.7359307359307359

Reporte de clasificación:
               precision    recall  f1-score   support

           0       0.80      0.79      0.80       151
           1       0.62      0.62      0.62        80

    accuracy                           0.74       231
   macro avg       0.71      0.71      0.71       231
weighted avg       0.74      0.74      0.74       231



***EJERCICIO TRES***

In [93]:
# Cargar datos
url = "https://raw.githubusercontent.com/arib168/data/main/Social_Network_Ads.csv"
data = pd.read_csv(url)

print(f"Datos cargados: {data.shape[0]} filas y {data.shape[1]} columnas")
print(data.head(20))

Datos cargados: 400 filas y 5 columnas
     User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510    Male   19            19000          0
1   15810944    Male   35            20000          0
2   15668575  Female   26            43000          0
3   15603246  Female   27            57000          0
4   15804002    Male   19            76000          0
5   15728773    Male   27            58000          0
6   15598044  Female   27            84000          0
7   15694829  Female   32           150000          1
8   15600575    Male   25            33000          0
9   15727311  Female   35            65000          0
10  15570769  Female   26            80000          0
11  15606274  Female   26            52000          0
12  15746139    Male   20            86000          0
13  15704987    Male   32            18000          0
14  15628972    Male   18            82000          0
15  15697686    Male   29            80000          0
16  15733883    Male   47            25000 

In [94]:
compraron = data[data['Purchased'] == 1]
print(compraron.head(20))  # Mostrar las primeras filas de los que compraron

      User ID  Gender  Age  EstimatedSalary  Purchased
7    15694829  Female   32           150000          1
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
31   15729054  Female   27           137000          1
48   15727696    Male   30           135000          1
63   15583681    Male   32           120000          1
75   15651983    Male   34           112000          1
85   15663

In [95]:
edadMayor = data[data['Age'] <= 22]
print(edadMayor.head(20))

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
4    15804002    Male   19            76000          0
12   15746139    Male   20            86000          0
14   15628972    Male   18            82000          0
32   15573452  Female   21            16000          0
51   15764195  Female   18            44000          0
58   15642885    Male   22            18000          0
68   15577178  Female   22            63000          0
72   15595228  Female   20            23000          0
76   15746737    Male   18            52000          0
77   15774179  Female   22            27000          0
82   15709476    Male   20            49000          0
90   15684801    Male   22            81000          0
104  15672091  Female   19            21000          0
105  15801658    Male   21            72000          0
133  15638963  Female   21            68000          0
136  15668504  Female   20            82000          0
139  15741

In [96]:
# Seleccionar características y objetivo
X = data[['Age', 'EstimatedSalary']]
y = data['Purchased']

# Estandarizar características
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [97]:
# Dividir datos
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Crear y entrenar modelo
from sklearn.linear_model import LogisticRegression
modelo = LogisticRegression()
modelo.fit(X_train, y_train)

LogisticRegression()

In [98]:
# Evaluar modelo
y_pred = modelo.predict(X_test)
print("Exactitud:", accuracy_score(y_test, y_pred))
print("\nReporte de clasificación:\n", classification_report(y_test, y_pred))

Exactitud: 0.85

Reporte de clasificación:
               precision    recall  f1-score   support

           0       0.82      0.97      0.89        73
           1       0.94      0.66      0.78        47

    accuracy                           0.85       120
   macro avg       0.88      0.82      0.83       120
weighted avg       0.86      0.85      0.84       120



In [107]:
# Función para predecir compra con nuevos datos
def predecir_compra(edad, salario):
    # Crear dataframe con los datos nuevos
    datos_nuevos = pd.DataFrame([[edad, salario]], columns=['Age', 'EstimatedSalary'])
    
    # Escalar datos usando el scaler original
    datos_nuevos_scaled = scaler.transform(datos_nuevos)
    
    # Predecir con el modelo
    prediccion = modelo.predict(datos_nuevos_scaled)
    probabilidad = modelo.predict_proba(datos_nuevos_scaled)[0][1]  # probabilidad de comprar (clase 1)
    
    if prediccion[0] == 1:
        print(f"Predicción: La persona probablemente COMPRARÁ el producto (Probabilidad: {probabilidad:.2f})")
    else:
        print(f"Predicción: La persona probablemente NO COMPRARÁ el producto (Probabilidad: {probabilidad:.2f})")

# Ejemplo de uso:
edad_input = float(input("Ingresa la edad: "))
salario_input = float(input("Ingresa el salario estimado: "))

print(f"Salario estimado: {salario_input}")
print(f"Edad: {edad_input}")
predecir_compra(edad_input, salario_input)

Salario estimado: 80000.0
Edad: 30.0
Predicción: La persona probablemente NO COMPRARÁ el producto (Probabilidad: 0.10)
